services:
  # Basic API with no auth
  api-noauth:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AUTH_MODE=none

  # API with basic auth
  api-basic:
    build: .
    ports:
      - "8081:8080"
    environment:
      - AUTH_MODE=basic
      - BASIC_USER=user
      - BASIC_PASS=pass
